"""Test include_object

Revision ID: f77223e10803
Revises: 
Create Date: 2024-11-23 19:33:05.221531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f77223e10803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mot_de_passe', sa.String(length=255), nullable=False))
        batch_op.drop_column('ID_USER')
        batch_op.drop_column('USERNAME')
        batch_op.drop_column('MOT_DE_PASSE')
        batch_op.drop_column('EMAIL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EMAIL', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('MOT_DE_PASSE', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('USERNAME', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ID_USER', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('mot_de_passe')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('id_user')

    op.drop_table('posts')
    # ### end Alembic commands ###
